;; This code was automatically generated by the 'metav' library.
(ns demo.version)

(def module-name "bh-lib")
(def path ".")
(def version "3.1.0-0xb279.DIRTY")
(def tag "v3.1.0-0xb279.DIRTY")
(def generated-at "2023-10-11T17:11:27Z")
