;; This code was automatically generated by the 'metav' library.
(ns demo.version)

(def module-name "bh-lib")
(def path ".")
(def version "3.1.0-0x8245")
(def tag "v3.1.0-0x8245")
(def generated-at "2023-10-19T15:11:51Z")
