;; This code was automatically generated by the 'metav' library.
(ns demo.version)

(def module-name "bh-lib")
(def path ".")
(def version "3.1.0-0x507f")
(def tag "v3.1.0-0x507f")
(def generated-at "2023-10-20T02:02:20Z")
