;; This code was automatically generated by the 'metav' library.
(ns bh-ui.version)

(def module-name "bh-lib")
(def path ".")
(def version "3.2.1")
(def tag "v3.2.1")
(def generated-at "2023-12-01T20:11:46Z")
