;; This code was automatically generated by the 'metav' library.
(ns bh-ui.version)

(def module-name "bh-lib")
(def path ".")
(def version "3.1.0-0x64a9")
(def tag "v3.1.0-0x64a9")
(def generated-at "2023-10-27T22:27:26Z")
