;; This code was automatically generated by the 'metav' library.
(ns bh-ui.version)

(def module-name "bh-lib")
(def path ".")
(def version "3.1.0-0x2dbb")
(def tag "v3.1.0-0x2dbb")
(def generated-at "2023-10-21T01:36:09Z")
